/** Resolved builder theme tokens with safe fallbacks. */
export function resolveBuilderTheme({
  designBackground = '#f0eee8',
  designTextColor = '#198eea',
  formAccentColor = '#3b7bf6',
  designCardColor = '#f9f9fa',
  designCardOpacity = 74,
  designCardImage = null,
  designLayoutStyle = 'withCard',
  hexToRgba,
}) {
  const rgba = typeof hexToRgba === 'function' ? hexToRgba : (hex, opacity) => hex;
  return {
    canvasBackground: designBackground ?? '#f0eee8',
    textColor: designTextColor || '#111111',
    accentColor: designTextColor || formAccentColor || '#111111',
    cardColor: rgba(designCardColor ?? '#f9f9fa', designCardOpacity ?? 74),
    cardImage: designCardImage ?? null,
    fullCanvas: designLayoutStyle === 'fullCanvas',
  };
}

/**
 * Canvas field configs: values + setters so Configure panel and ContentCard share one state loop.
 */
export function buildCanvasFieldConfigs({
  // CTA
  ctaButtonLabel,
  ctaHeadingText,
  ctaHelperText,
  ctaDurationText,
  ctaButtonSize,
  ctaButtonStyle,
  ctaCornerRadius,
  ctaShowIcon,
  ctaHeadingSize,
  ctaBodySize,
  ctaFontWeight,
  ctaTextAlign,
  ctaPadding,
  ctaTextColor,
  ctaBtnColor,
  ctaLabelColor,
  ctaContentWidth,
  isEditingCtaCard,
  setIsEditingCtaCard,
  setCtaHeadingText,
  setCtaHelperText,
  setCtaDurationText,
  // Heading
  headingText,
  subHeading,
  headingRequired,
  headingHidden,
  headingLevel,
  headingTextSize,
  headingAlignment,
  headingFontWeight,
  headingAnswerText,
  isEditingHeadingCard,
  setIsEditingHeadingCard,
  setHeadingText,
  setSubHeading,
  setHeadingAnswerText,
  // Description
  descriptionContent,
  descriptionHidden,
  descriptionShowCharCount,
  descriptionCharLimit,
  descriptionFormatting,
  descriptionTextSize,
  descriptionAlignment,
  setDescriptionContent,
  // Image
  imageHidden,
  imagePreview,
  imageAltText,
  imageCaption,
  imageLinkOnClick,
  imageLinkUrl,
  imageOpenInNewTab,
  imageAlignment,
  imageWidth,
  imageCornerRadius,
  imageQuestion,
  imageDescription,
  setImagePreview,
  setImageFileName,
  setImageCaption,
  setImageQuestion,
  setImageDescription,
  // Video
  videoUrl,
  videoCaption,
  videoWidth,
  videoAspectRatio,
  videoCornerRadius,
  videoQuestion,
  videoDescription,
  videoRequired,
  videoHidden,
  videoLoop,
  videoAutoplay,
  videoShowControls,
  videoSource,
  setVideoCaption,
  setVideoQuestion,
  setVideoDescription,
  // Contact
  contactQuestion,
  contactHelperText,
  contactFields,
  contactRequired,
  setContactQuestion,
  setContactHelperText,
  // Address
  addressQuestion,
  addressHelperText,
  addressFields,
  addressRequired,
  setAddressQuestion,
  setAddressHelperText,
  // Work
  workQuestion,
  workHelperText,
  workFields,
  workRequired,
  setWorkQuestion,
  setWorkHelperText,
  // Short / long text
  shortTextQuestion,
  shortTextHelperText,
  shortTextPlaceholder,
  shortTextMaxChars,
  shortTextMinChars,
  shortTextValidation,
  shortTextAlign,
  shortTextSize,
  shortTextRequired,
  shortTextHidden,
  shortTextResponseQualityEnabled,
  shortTextResponseQualityOptions,
  setShortTextQuestion,
  setShortTextHelperText,
  setShortTextPlaceholder,
  longTextQuestion,
  longTextHelperText,
  longTextPlaceholder,
  longTextMaxChars,
  longTextMinChars,
  longTextValidation,
  longTextAlign,
  longTextSize,
  longTextRequired,
  longTextHidden,
  responseQualityEnabled,
  responseQualityOptions,
  setLongTextQuestion,
  setLongTextHelperText,
  setLongTextPlaceholder,
  // Choice
  singleQuestion,
  singleHelperText,
  singleOptions,
  singleLayout,
  singleOptionHeight,
  singleRequired,
  singleAllowOther,
  singleRandomize,
  singleMultipleSelect,
  singleMinChoices,
  singleMaxChoices,
  singleShowKeyboardHints,
  setSingleQuestion,
  setSingleHelperText,
  multipleQuestion,
  multipleHelperText,
  multipleOptions,
  multipleLayout,
  multipleRequired,
  multipleAllowOther,
  multipleRandomize,
  multipleMultipleSelect,
  multipleMinChoices,
  multipleMaxChoices,
  multipleShowKeyboardHints,
  multipleOptionHeight,
  setMultipleQuestion,
  setMultipleHelperText,
  mediaQuestion,
  mediaHelperText,
  mediaOptions,
  mediaAllowMultiple,
  mediaRequired,
  mediaRandomiseOrder,
  mediaMinChoices,
  mediaMaxChoices,
  mediaLayout,
  mediaOptionHeight,
  setMediaQuestion,
  setMediaHelperText,
  // Captcha / upload / rating / date / time
  captchaProvider,
  captchaSiteKey,
  captchaEnabled,
  captchaVisibility,
  multiImageQuestion,
  multiImageHelperText,
  multiImageMaxFiles,
  multiImageRequired,
  multiImageMultipleFiles,
  multiImageMaxFileSize,
  setMultiImageQuestion,
  setMultiImageHelperText,
  uploadQuestion,
  uploadHelperText,
  uploadMaxFileSize,
  setUploadQuestion,
  setUploadHelperText,
  ratingQuestion,
  ratingRequired,
  ratingUseScale,
  ratingUseSlider,
  ratingMaxRating,
  ratingStyle,
  ratingLowLabel,
  ratingHighLabel,
  ratingShowLabels,
  ratingIconSize,
  setRatingQuestion,
  setRatingLowLabel,
  setRatingHighLabel,
  dateQuestion,
  dateHelperText,
  dateRequired,
  setDateQuestion,
  setDateHelperText,
  timeQuestion,
  timeHelperText,
  timeRequired,
  timeUse12h,
  timeShowSeconds,
  timeMinTime,
  timeMaxTime,
  setTimeQuestion,
  setTimeHelperText,
  openSingleConfigPanel,
  openMultipleConfigPanel,
}) {
  return {
    ctaConfig: {
      ctaButtonLabel,
      ctaHeadingText,
      ctaHelperText,
      ctaDurationText,
      ctaButtonSize,
      ctaButtonStyle,
      ctaCornerRadius,
      ctaShowIcon,
      ctaHeadingSize,
      ctaBodySize,
      ctaFontWeight,
      ctaTextAlign,
      ctaPadding,
      ctaTextColor,
      ctaBtnColor,
      ctaLabelColor,
      ctaContentWidth,
      isEditingCard: isEditingCtaCard,
      onEditToggle: () => setIsEditingCtaCard((p) => !p),
      setCtaHeadingText,
      setCtaHelperText,
      setCtaDurationText,
    },
    headingConfig: {
      headingText,
      subHeading,
      headingRequired,
      headingHidden,
      headingLevel,
      headingTextSize,
      headingAlignment,
      headingFontWeight,
      isEditingCard: isEditingHeadingCard,
      onEditToggle: () => setIsEditingHeadingCard((p) => !p),
      setHeadingText,
      setSubHeading,
      headingAnswerText,
      setHeadingAnswerText,
    },
    descriptionConfig: {
      descriptionContent,
      descriptionHidden,
      descriptionShowCharCount,
      descriptionCharLimit,
      descriptionFormatting,
      descriptionTextSize,
      descriptionAlignment,
      setDescriptionContent,
    },
    imageConfig: {
      imageHidden,
      imagePreview,
      imageAltText,
      imageCaption,
      imageLinkOnClick,
      imageLinkUrl,
      imageOpenInNewTab,
      imageAlignment,
      imageWidth,
      imageCornerRadius,
      imageQuestion,
      imageDescription,
      setImageCaption,
      setImageQuestion,
      setImageDescription,
      onRemoveImage: () => {
        setImagePreview(null);
        setImageFileName('');
      },
    },
    videoConfig: {
      videoUrl,
      videoCaption,
      videoWidth,
      videoAspectRatio,
      videoCornerRadius,
      videoQuestion,
      videoDescription,
      videoRequired,
      videoHidden,
      videoLoop,
      videoAutoplay,
      videoShowControls,
      videoSource,
      setVideoCaption,
      setVideoQuestion,
      setVideoDescription,
    },
    contactConfig: {
      contactQuestion,
      contactHelperText,
      contactFields,
      contactRequired,
      setContactQuestion,
      setContactHelperText,
    },
    addressConfig: {
      addressQuestion,
      addressHelperText,
      addressFields,
      addressRequired,
      setAddressQuestion,
      setAddressHelperText,
    },
    workConfig: {
      workQuestion,
      workHelperText,
      workFields,
      workRequired,
      setWorkQuestion,
      setWorkHelperText,
    },
    shortTextConfig: {
      shortTextQuestion,
      shortTextHelperText,
      shortTextPlaceholder,
      shortTextMaxChars,
      shortTextMinChars,
      shortTextValidation,
      shortTextAlign,
      shortTextSize,
      shortTextRequired,
      shortTextHidden,
      setShortTextQuestion,
      setShortTextHelperText,
      setShortTextPlaceholder,
    },
    shortTextResponseQualityConfig: {
      enabled: shortTextResponseQualityEnabled,
      options: shortTextResponseQualityOptions,
    },
    longTextConfig: {
      longTextQuestion,
      longTextHelperText,
      longTextPlaceholder,
      longTextMaxChars,
      longTextMinChars,
      longTextValidation,
      longTextAlign,
      longTextSize,
      longTextRequired,
      longTextHidden,
      setLongTextQuestion,
      setLongTextHelperText,
      setLongTextPlaceholder,
    },
    longTextResponseQualityConfig: {
      enabled: responseQualityEnabled,
      options: responseQualityOptions,
    },
    singleConfig: {
      singleQuestion,
      singleHelperText,
      singleOptions,
      singleLayout,
      singleOptionHeight,
      singleRequired,
      singleAllowOther,
      singleRandomize,
      singleMultipleSelect,
      singleMinChoices,
      singleMaxChoices,
      singleShowKeyboardHints,
      setSingleQuestion,
      setSingleHelperText,
      onOpenPanel: openSingleConfigPanel,
    },
    multipleConfig: {
      multipleQuestion,
      multipleHelperText,
      multipleOptions,
      multipleLayout,
      multipleRequired,
      multipleAllowOther,
      multipleRandomize,
      multipleMultipleSelect,
      multipleMinChoices,
      multipleMaxChoices,
      multipleShowKeyboardHints,
      multipleOptionHeight,
      setMultipleQuestion,
      setMultipleHelperText,
      onOpenPanel: openMultipleConfigPanel,
    },
    mediaConfig: {
      mediaQuestion,
      mediaHelperText,
      mediaOptions,
      mediaAllowMultiple,
      mediaRequired,
      mediaRandomiseOrder,
      mediaMinChoices,
      mediaMaxChoices,
      mediaLayout,
      mediaOptionHeight,
      setMediaQuestion,
      setMediaHelperText,
    },
    captchaConfig: {
      captchaProvider,
      captchaSiteKey,
      captchaEnabled,
      captchaVisibility,
    },
    multiImageConfig: {
      question: multiImageQuestion,
      helperText: multiImageHelperText,
      maxFiles: multiImageMaxFiles,
      required: multiImageRequired,
      multipleFiles: multiImageMultipleFiles,
      maxFileSize: multiImageMaxFileSize,
      setQuestion: setMultiImageQuestion,
      setHelperText: setMultiImageHelperText,
    },
    uploadConfig: {
      question: uploadQuestion,
      helperText: uploadHelperText,
      maxFileSize: uploadMaxFileSize,
      setQuestion: setUploadQuestion,
      setHelperText: setUploadHelperText,
    },
    ratingConfig: {
      ratingQuestion,
      ratingRequired,
      ratingUseScale,
      ratingUseSlider,
      ratingMaxRating,
      ratingStyle,
      ratingLowLabel,
      ratingHighLabel,
      ratingShowLabels,
      ratingIconSize,
      setRatingQuestion,
      setRatingLowLabel,
      setRatingHighLabel,
    },
    dateConfig: {
      dateQuestion,
      dateHelperText,
      dateRequired,
      setDateQuestion,
      setDateHelperText,
    },
    timeConfig: {
      timeQuestion,
      timeHelperText,
      timeRequired,
      timeUse12h,
      timeShowSeconds,
      timeMinTime,
      timeMaxTime,
      setTimeQuestion,
      setTimeHelperText,
    },
  };
}

export const FIELD_LABEL_TO_CONFIG_PANEL = {
  CTA: 'ctaConfig',
  Heading: 'headingConfig',
  Description: 'descriptionConfig',
  Images: 'imageConfig',
  Video: 'videoConfig',
  Contact: 'contactConfig',
  Address: 'addressConfig',
  'Work Info': 'workConfig',
  'Short text': 'shortTextConfig',
  'Long text': 'longTextConfig',
  Single: 'singleConfig',
  Multiple: 'multipleConfig',
  Media: 'mediaConfig',
  Captcha: 'captchaConfig',
  'Multi-image upload': 'multiImageConfig',
  Upload: 'multiImageConfig',
  Rating: 'ratingConfig',
  Date: 'dateConfig',
  Time: 'timeConfig',
};
