/** Full preview blocks for onboarding template modal (14 questions). */
export const DEFAULT_TEMPLATE_PREVIEW_BLOCKS = [
  {
    type: 'welcome',
    label: 'Welcome screen',
    title: 'Welcome to our survey',
    description:
      'Please fill out this form to help us improve. It only takes a couple of minutes.',
  },
  {
    type: 'section',
    label: 'Section heading',
    title: 'Tell us about yourself',
    description: 'This section covers your professional background and preferences.',
  },
  {
    type: 'question',
    num: 1,
    label: 'Contact',
    title: 'How can we get in touch?',
    description: "We'll only reach out if we have a follow-up question.",
    fields: ['Jane', 'Smith', 'jane@example.com', '+1 (555) 000-0000'],
  },
  {
    type: 'question',
    num: 2,
    label: 'Address',
    title: "What's your mailing address?",
    fields: ['123 Main Street', 'San Francisco', 'California', '94102'],
  },
  {
    type: 'question',
    num: 3,
    label: 'Short text',
    title: 'What is your current job title?',
    fields: ['Senior Product Designer'],
  },
  {
    type: 'question',
    num: 4,
    label: 'Long text',
    title: 'Describe your relevant experience for this role.',
    description: 'Include years of experience, key skills, and notable achievements.',
    fields: ['Share your professional background and why you are a strong fit…'],
  },
  {
    type: 'question',
    num: 5,
    label: 'Multiple choice',
    title: 'What is your highest level of education?',
    fields: ['Bachelor\'s degree', 'Master\'s degree', 'Doctorate', 'Other'],
  },
  {
    type: 'section',
    label: 'Section heading',
    title: 'Role preferences',
    description: 'Help us understand your availability and expectations.',
  },
  {
    type: 'question',
    num: 6,
    label: 'Dropdown',
    title: 'When could you start?',
    fields: ['Select an option'],
  },
  {
    type: 'question',
    num: 7,
    label: 'Yes / No',
    title: 'Are you open to remote work?',
    fields: ['Yes', 'No'],
  },
  {
    type: 'question',
    num: 8,
    label: 'Number',
    title: 'What are your salary expectations (USD)?',
    fields: ['120000'],
  },
  {
    type: 'question',
    num: 9,
    label: 'File upload',
    title: 'Upload your résumé',
    description: 'PDF or Word document, max 10 MB.',
    fields: ['Drop file here or click to browse'],
  },
  {
    type: 'question',
    num: 10,
    label: 'URL',
    title: 'Link to your portfolio or LinkedIn',
    fields: ['https://linkedin.com/in/janesmith'],
  },
  {
    type: 'question',
    num: 11,
    label: 'Rating',
    title: 'How confident are you in your fit for this role?',
    fields: ['1', '2', '3', '4', '5'],
  },
  {
    type: 'question',
    num: 12,
    label: 'Checkboxes',
    title: 'Which tools are you proficient in?',
    fields: ['Figma', 'Notion', 'Jira', 'Slack', 'Other'],
  },
  {
    type: 'question',
    num: 13,
    label: 'Date',
    title: 'When did you last update your portfolio?',
    fields: ['MM / DD / YYYY'],
  },
  {
    type: 'question',
    num: 14,
    label: 'Long text',
    title: 'Anything else we should know?',
    description: 'Optional — share context that would help us evaluate your application.',
    fields: ['Your answer…'],
  },
];

export const TEMPLATE_PREVIEW_META = {
  questionCount: 14,
  duration: '~6 minutes',
  structure: 'Multi-section',
};
